### ISSUE TITLE
Get all available beacons list

### ISSUE THREAD

**Issue by Gob-Lin** [igor-makarov/BeaconKit#1]
Hello,

is it possible to get the list of all available beacons in one go, instead of one at the time?
Or, if this is not possible, to detect when a previously detected beacon is not visible anymore?

Thank you,

H

**Comment by igor-makarov** [comment]
Unfortunately, both of these things are impossible due to the underlying CoreBluetooth frameworks, and, I believe, the BTLE protocol itself. 

Firstly, most beacons have an advertising rate which can be controlled by beacon owner. This rate is usually very high (1 second or less) and affects beacon battery life.
Secondly, CoreBluetooth determines the scan frequency using its own heuristics, and this can go between immediate and 40 seconds when in foreground. [Here's some more info I've found](https://stackoverflow.com/questions/47314009/corebluetooth-scan-detection-times-unreliable-on-macos).

In my own usage, I'm aggregating all detected beacons into windows of 10 seconds and hope for the best.

**Comment by Gob-Lin** [comment]
Thanks Igor,

I followed the same strategy, 5 seconds window and fingers crossed :-) 
I guess it's the only thing to do at the moment.
